apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(10000)"]
          restartPolicy: Never
      backoffLimit: 1
