apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: default
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "true"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: workloads.me # TODO(waltforme): double check this
  - name: Service
    value: el-getting-started-listener
  - name: ServicePort
    value: "8080"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
