apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            # replaced index.html with my-index.html
            index  my-index.html index.htm;
        }
      }
    }
