apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ensure-latest-kyst-custom-resources
spec:
  description: |
    features of ensure-latest-kyst-custom-resources:
      - Using the git-clone catalog Task to clone a branch
      - Passing a cloned repo to subsequent Tasks using a Workspace.
      - Ordering Tasks in a Pipeline using "runAfter" so that
        git-clone completes before we try to read from the Workspace.
      - Using a volumeClaimTemplate Volume as a Workspace.
      - Avoiding hard-coded paths by using a Workspace's path
        variable instead.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: revision
    type: string
    description: The git revision to checkout.
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.revision)
  - name: wrap-for-kyst
    runAfter: ["fetch-repo"]
    taskRef:
      name: wrap4kyst
    workspaces:
    - name: updates
      workspace: shared-data
  - name: show-configspec
    runAfter: ["fetch-repo", "wrap-for-kyst"]
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      steps:
      - name: cat
        image: zshusers/zsh:4.3.15
        script: |
          #!/usr/bin/env zsh
          cat $(workspaces.source.path)/kubernetes/guestbook/deploy/configspec.yaml
  - name: apply-manifests
    runAfter: ["fetch-repo", "wrap-for-kyst", "show-configspec"]
    taskRef:
      name: apply
    workspaces:
    - name: wrapped
      workspace: shared-data
