apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: xl-release
    meta.helm.sh/release-namespace: turbonomic
  creationTimestamp: "2022-09-27T21:45:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: turbo-all-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: turbo-user
  namespace: turbonomic
