apiVersion: v1
data:
  turbo.config: |-
    {
      "communicationConfig": {
        "serverMeta": {
          "version": "8.6.2",
          "turboServer": "http://172.31.17.224:30180"
        },
        "restAPIConfig": {
          "opsManagerUserName": "Turbo_username",
          "opsManagerPassword": "Turbo_password"
        }
      },
      "HANodeConfig": {
        "nodeRoles": ["master"]
      },
      "targetConfig": {
        "targetName": "Turbonomic"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: xl-release
    meta.helm.sh/release-namespace: turbonomic
  creationTimestamp: "2022-09-27T21:45:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: turbo-config-xl-release
  namespace: turbonomic
  ownerReferences:
  - apiVersion: charts.helm.k8s.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Xl
    name: xl-release
    uid: 8c5a5aa4-7f51-4dd8-bc00-0bd84fff972f
