apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: xl-release
    meta.helm.sh/release-namespace: turbonomic
  creationTimestamp: "2022-09-27T21:45:33Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: xl-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeturbo
    helm.sh/chart: kubeturbo-1.0.0
  name: kubeturbo
  namespace: turbonomic
  ownerReferences:
  - apiVersion: charts.helm.k8s.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Xl
    name: xl-release
    uid: 8c5a5aa4-7f51-4dd8-bc00-0bd84fff972f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: xl-release
      app.kubernetes.io/name: kubeturbo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubeturbo.io/controllable: "false"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: xl-release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kubeturbo
    spec:
      containers:
      - args:
        - --turboconfig=/etc/kubeturbo/turbo.config
        - --v=2
        - --kubelet-https=true
        - --kubelet-port=10250
        image: turbonomic/kubeturbo:8.6.2
        imagePullPolicy: IfNotPresent
        name: kubeturbo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubeturbo
          name: turbo-volume
          readOnly: true
        - mountPath: /etc/turbonomic-credentials
          name: turbonomic-credentials-volume
          readOnly: true
        - mountPath: /var/log
          name: varlog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
      serviceAccount: turbo-user
      serviceAccountName: turbo-user
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: turbo-config-xl-release
        name: turbo-volume
      - name: turbonomic-credentials-volume
        secret:
          defaultMode: 420
          optional: true
          secretName: turbonomic-credentials
      - emptyDir: {}
        name: varlog
