---
apiVersion: scheduling.kcp.io/v1alpha1
kind: Placement
metadata:
  name: green
spec:
  locationResource:
    group: workload.kcp.io
    resource: synctargets
    version: v1alpha1
  locationSelectors:
  - matchLabels:
      color: green
  locationWorkspace: root:my-org:edge
  namespaceSelector:
    matchLabels:
      color: green
---
apiVersion: scheduling.kcp.io/v1alpha1
kind: Placement
metadata:
  name: blue
spec:
  locationResource:
    group: workload.kcp.io
    resource: synctargets
    version: v1alpha1
  locationSelectors:
  - matchLabels:
      color: blue
  locationWorkspace: root:my-org:edge
  namespaceSelector:
    matchLabels:
      color: blue
