apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ensure-latest-kyst-custom-resources-run
spec:
  serviceAccountName: tekton-kyst
  pipelineRef:
    name: ensure-latest-kyst-custom-resources
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/edge-experiments/gitops-source.git
  - name: revision
    value: main
