apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue

resources:
- ../manifests

patchesStrategicMerge:
- configmap-my-index.yaml

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: blue-nginx
  target:
    kind: Service
  options:
    allowNameChange: true
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 0
    - op: replace
      path: /metadata/name
      value: blue-nginx
  target:
    kind: Deployment
  options:
    allowNameChange: true
