---
apiVersion: edge.kcp.io/v1alpha1
kind: EdgePlacement
metadata:
  name: optimized
spec:
  locationSelectors:
  - matchLabels:
      aisle: "2"
  namespaceSelector:
    matchLabels:
      optimizer: turbonomic
